<a href="https://colab.research.google.com/github/LearningAIFun/Pytorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
my_list =[1,2,3,4]
my_list

[1, 2, 3, 4]

In [4]:
my_list2 =[ [1,2,3], [2,3,4]]
my_list2

[[1, 2, 3], [2, 3, 4]]

Numpy arrays

In [6]:
np1 =  np.random.rand(3,4)
np1

array([[0.64974469, 0.75812464, 0.5892714 , 0.6334112 ],
       [0.51913653, 0.90309887, 0.47893562, 0.98611497],
       [0.85991576, 0.03453784, 0.29167504, 0.31121421]])

In [7]:
np1.dtype

dtype('float64')

Tensors

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 2.2390, -1.1205, -0.2372,  0.8043],
        [ 0.1964,  0.4262,  0.3260,  0.5953],
        [ 1.6054, -1.3329,  0.1420, -0.6333]])

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6497, 0.7581, 0.5893, 0.6334],
        [0.5191, 0.9031, 0.4789, 0.9861],
        [0.8599, 0.0345, 0.2917, 0.3112]], dtype=torch.float64)

In [12]:
x_np = torch.from_numpy(np1)
my_tensor == x_np

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [14]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [15]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3727, 0.4399],
        [0.0614, 0.1978]]) 

